### ISSUE TITLE
默认图片

### ISSUE THREAD

**Issue by loyilin** [goyourfly/MultiPictureView#1]
这个控件创意很不错啊，使我开发减少了不少工作量，谢谢你，在使用中遇到了几个问题，希望大神能解决下呀
720*480手机上显示的默认加号非常模糊

**Comment by goyourfly** [comment]
@1913656443 你可以使用<app:addDrawable="@drawable/..."> 替换默认的加号

**Comment by loyilin** [comment]
谢谢，我已经使用了我自己的图片

**Comment by goyourfly** [comment]
@1913656443 👌
